#include <stdio.h>
#include <unistd.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>     // Add this for extra safety
#include "hello.skel.h"  // The skeleton generated by bpftool

// Define the struct if it's not being picked up
struct hello_bpf; 

int main() {
    struct hello_bpf *skel;
    int err;

    skel = hello_bpf__open_and_load();
    if (!skel) return 1;

    err = hello_bpf__attach(skel);
    if (err) goto cleanup;

    printf("BPF program loaded. Check /sys/kernel/debug/tracing/trace_pipe\n");

    // Keep the program running
    while (1) {
        sleep(1);
    }

cleanup:
    hello_bpf__destroy(skel);
    return 0;
}